Repository Auth0r-C0dez/Caption_generator, pull requests merged in 2025-01, with the labels that each got.

#5 Docs: create requirements.txt
  README.md
  requirements.txt
Labels: acwoc, medium

#11 Enhanced AI-Powered Caption Generator with Context-Aware Features
  Source_code.py
Labels: acwoc, medium

#13 Adding Visual Question Answering Feature
  README.md
  Source_code.py
  requirements.txt
Labels: acwoc, hard

#16 Adding Object Detection in Image
  .gitignore
  README.md
  Source_code.py
  requirements.txt
Labels: documentation, enhancement, acwoc, hard

#18 Completed :- Extract text from images Feature
  .gitignore
  README.md
  Source_code.py
  assets/images/Screenshot 2024-11-17 133404.png
  assets/images/Screenshot 2024-11-17 133441.png
  requirements.txt
Labels: enhancement, acwoc, hard

#19 Update Source_code.py
  Source_code.py
Labels: acwoc, medium
